src/constructor/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path

from . import views

app_name = 'constructor'

urlpatterns = [
    path('delete/<int:quiz_id>/', views.delete_quiz, name='delete_quiz'),
    path('login/', views.login_create_quiz, name='login_create_quiz'),
    path('', views.create_quiz, name='create_quiz'),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

src/core/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('constructor/', include('constructor.urls', namespace='constructor')),
    path('', include('quizzing.urls', namespace='quizzing')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

src/quizzing/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path

from . import views

app_name = 'quizzing'

urlpatterns = [
    path('pass/<int:quiz_pk>/<int:question_pk>/', views.pass_quiz, name='pass_quiz'),
    path('pass/<int:quiz_pk>/', views.pass_quiz, name='pass_quiz'),
    path('', views.select_quiz, name='select_quiz'),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

src/constructor/models.py
from django.db import models
from django.utils.translation import gettext_lazy as _


class Category(models.Model):
    """Model for keeping category of question."""
    name = models.CharField(max_length=255, verbose_name=_('название'))
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = _('блок')
        verbose_name_plural = _('блоки')


class Subcategory(models.Model):
    """Model for keeping subcategory of question."""
    category = models.ForeignKey(
        Category,
        on_delete=models.CASCADE,
        related_name='subcategories',
        verbose_name=_('блок'),
    )
    name = models.CharField(max_length=255, verbose_name=_('название'))
    amount = models.PositiveSmallIntegerField(default=10, verbose_name=_('количество вопросов в подкатегории'))
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = _('подблок')
        verbose_name_plural = _('подблоки')


class Question(models.Model):
    """Model for keeping test question."""
    subcategory = models.ForeignKey(
        Subcategory,
        on_delete=models.CASCADE,
        related_name='questions',
        verbose_name=_('подблок'),
    )
    text = models.TextField(verbose_name=_('содержание вопроса'))
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.text

    class Meta:
        verbose_name = _('вопрос')
        verbose_name_plural = _('вопросы')


class Answer(models.Model):
    """Model for keeping answer for test question."""
    text = models.TextField(verbose_name=_('содержание ответа'))
    question = models.ForeignKey(Question, on_delete=models.CASCADE, related_name='answers', verbose_name=_('вопрос'))
    is_right = models.BooleanField(default=False, verbose_name=_('ответ верен?'))
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.text

    class Meta:
        ordering = ('question',)
        verbose_name = _('ответ')
        verbose_name_plural = _('ответы')

src/constructor/forms.py
from django import forms
from django.utils.translation import gettext_lazy as _

from .models import Subcategory


class CustomModelChoiceIterator(forms.models.ModelChoiceIterator):
    def choice(self, obj):
        return (
            forms.models.ModelChoiceIteratorValue(self.field.prepare_value(obj), obj),
            self.field.label_from_instance(obj),
            obj,
        )


class CustomModelChoiceField(forms.models.ModelMultipleChoiceField):
    def _get_choices(self):
        if hasattr(self, '_choices'):
            return self._choices
        return CustomModelChoiceIterator(self)
    choices = property(_get_choices, forms.MultipleChoiceField._set_choices)


class CreateQuizForm(forms.Form):
    username = forms.CharField(
        label=_('Ф.И.О. тестируемого'),
        widget=forms.TextInput(attrs={'placeholder': 'Ф.И.О.'}),
        error_messages={'required': _('Необходимо ввести имя')},
    )
    subcategories = CustomModelChoiceField(
        queryset=Subcategory.objects.all(),
        widget=forms.CheckboxSelectMultiple,
        label=_('Блоки'),
        error_messages={'required': _('Необходимо выбрать хотя бы один блок.')},
    )


class LoginCreateQuizForm(forms.Form):
    password = forms.CharField(
        widget=forms.PasswordInput(attrs={'autocomplete': 'on'}),
        label=_('Пароль'),
    )

src/constructor/views.py
from itertools import groupby

from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse

from quizzing.models import Quiz
from .forms import CreateQuizForm, LoginCreateQuizForm
from .models import Question, Category


def create_quiz(request):
    if request.method == 'POST':
        form = CreateQuizForm(request.POST)
        if form.is_valid():
            quiz = Quiz.objects.create(username=form.cleaned_data['username'])
            for subcategory in form.cleaned_data['subcategories']:
                amount = int(request.POST[f'amount_{subcategory.pk}'])
                quiz.questions.add(*Question.objects.filter(subcategory=subcategory)[:amount])
            return HttpResponseRedirect(reverse('constructor:create_quiz'))
    else:
        form = CreateQuizForm()
    quizzes = Quiz.objects.values('pk', 'username', 'created_at')
    for quiz in quizzes:
        quiz['categories'] = [category for category in Category.objects.filter(
            subcategories__questions__quizzes__pk=quiz['pk']).distinct().values_list('name', flat=True)]
        quiz['created_at'] = quiz['created_at'].strftime('%Y.%m.%d')
    quizzes = [(k, list(g)) for k, g in groupby(quizzes, key=lambda x: x['created_at'])]
    return render(request, 'constructor/create_quiz.html', {
        'form': form,
        'quizzes': quizzes,
    })


def delete_quiz(request, quiz_id: None):
    Quiz.objects.filter(pk=quiz_id).delete()
    return HttpResponseRedirect(reverse('constructor:create_quiz'))


def login_create_quiz(request):
    if request.method == 'POST':
        form = LoginCreateQuizForm(request.POST)
        if form.is_valid():
            pass
    else:
        form = LoginCreateQuizForm()
    return render(request, 'constructor/login_create_quiz.html', {'form': form})

src/constructor/templates/constructor/base.html
<!DOCTYPE html>
{% load static %}
{% url 'quizzing:select_quiz' as index_url %}
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="{% static 'constructor/css/bootstrap.min.css' %}" >
    <script defer src="{% static 'constructor/js/bootstrap.bundle.min.js' %}"></script>
    <link rel="icon" type="image/x-icon" href="{% static 'favicon.ico' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'constructor/css/style.css' %}">
    <title>Бухгалтерский тест</title>
</head>
<body>
    <header>
        <div class="logo-link">
            <a href="{{ index_url }}"><img src="{% static 'constructor/images/logo-link.png' %}" alt="Название портала"></a>
        </div>
    </header>
    <main>
        <div class="container-fluid">
            {% block content %}
            {% endblock %}
        </div>
    </main>
    <footer>
    </footer>
</body>
</html>

src/constructor/templates/constructor/create_quiz.html
{% extends 'constructor/base.html' %}
{% load widget_tweaks %}

{% block content %}
    <br>
    <ul class="row justify-content-between">
        <form action="" method="post" class="form col" novalidate>
            <h3 class="text-center">Конструктор</h3>
            {% csrf_token %}

            {# Render hidden fields. #}
            {{ form.non_field_errors }}
            {% for hidden_field in form.hidden_fields %}
                {{ hidden_field.errors }}
                {{ hidden_field }}
            {% endfor %}

            {# Render username. #}
            {{ form.username.label_tag }}
            <div class="invalid-feedback d-block">
                {{ form.username.errors }}
            </div>
            <div class="mb-3" style="max-width: 1000px;">
            {% if form.username.errors %}
                {% render_field form.username class="form-control is-invalid" %}
            {% elif form.is_bound %}
                {% render_field form.username class="form-control is-valid" %}
            {% else %}
                {% render_field form.username class="form-control" %}
            {% endif %}
            </div>
            {{ form.username.help_text }}

            {# Render subcategories. #}
            {{ form.subcategories.label_tag }}
            <div class="invalid-feedback d-block">
                {{ form.subcategories.errors }}
            </div>
            {% for value, label, obj in form.subcategories.field.choices %}
                <div class="input-group mb-3" style="max-width: 1000px;">
                    <span class="input-group-text w-75 text-wrap text-start"><label for="id_subcategories_{{ forloop.counter0 }}"><input type="checkbox" name="subcategories" value="{{ value }}" class="subcategory-checkbox" id="id_subcategories_{{ forloop.counter0 }}"> {{ label }}</label></span>
                    <input type="number" value="{{ obj.amount }}" class="form-control subcategory-amount invisible" name="amount_{{ value }}" id="id_subcategory_inputs_{{ forloop.counter0 }}">
                </div>
            {% endfor %}
            {{ form.subcategories.help_text }}
            <br>

            <button type="submit" class="btn btn-primary">Создать</button>
        </form>
        <ul class="list-group col">
            <h3 class="text-center">Список тестов</h3>
            {% for date, quizzes_ in quizzes %}
            <li class="list-group-item d-flex justify-content-between align-items-center mt-3 p-3 ps-1" data-bs-toggle="collapse" data-bs-target="#collapse-quiz-{{ forloop.counter }}">
                {{ date }}
            </li>
                <div class="collapse" id="collapse-quiz-{{ forloop.counter }}">
                    <ul class="list-group col">
                        {% for quiz in quizzes_ %}
                            <div class="d-flex">
                                <li class="list-group-item d-flex justify-content-between align-items-center list-group-item-primary ps-3 flex-grow-1" data-bs-toggle="collapse" data-bs-target="#collapse-username-{{ forloop.parentloop.counter}}{{forloop.counter }}">
                                    {{ quiz.username }}
                                </li>
                                <a href="delete/{{ quiz.pk }}" class="btn btn-outline-danger" aria-label="Delete">Удалить</a>
                            </div>
                            <div class="collapse" id="collapse-username-{{ forloop.parentloop.counter}}{{forloop.counter }}">
                                <ul class="list-group col">
                                    {% for category in quiz.categories %}
                                        <li class="list-group-item d-flex justify-content-between align-items-center list-group-item-secondary ps-4">
                                            {{ category }}
                                        </li>
                                    {% endfor %}
                                </ul>
                            </div>
                        {% endfor %}
                    </ul>
                </div>
            {% endfor %}
        </ul>
    </div>
    <script>
        // Show/hide inputs with amount values.
        let checkboxes = document.getElementsByClassName('subcategory-checkbox')
        let inputs = document.getElementsByClassName('subcategory-amount')
        Array.from(checkboxes).forEach(checkbox => {
            Array.from(inputs).forEach(input => {
                if (checkbox.value == input.name.split('_')[1]) {
                    checkbox.addEventListener('change', () => toggleInput(input));
                }
            })
        });
        function toggleInput(element) {
            element.classList.toggle('invisible');
        };
    </script>
{% endblock %}