src/core/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('constructor/', include('constructor.urls', namespace='constructor')),
    path('', include('quizzing.urls', namespace='quizzing')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

src/quizzing/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path

from . import views

app_name = 'quizzing'

urlpatterns = [
    path('pass/<int:quiz_pk>/<int:question_pk>/', views.pass_quiz, name='pass_quiz'),
    path('pass/<int:quiz_pk>/', views.pass_quiz, name='pass_quiz'),
    path('', views.select_quiz, name='select_quiz'),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

src/quizzing/models.py
from django.db import models
from django.utils.translation import gettext_lazy as _


class Quiz(models.Model):
    """Model for keeping quiz."""
    username = models.CharField(max_length=255, verbose_name=_('Ф.И.О. проверяемого'))
    questions = models.ManyToManyField(
        'constructor.Question',
        through='quizzing.QuizQuestion',
        related_name='quizzes',
        verbose_name=_('вопросы'),
    )
    is_completed = models.BooleanField(default=False, verbose_name=_('опрос пройден?'))
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.username

    class Meta:
        verbose_name = _('опрос')
        verbose_name_plural = _('опросы')


class QuizQuestion(models.Model):
    """Model for keeping info about question of quizz."""
    quiz = models.ForeignKey(Quiz, on_delete=models.CASCADE, related_name='quiz_questions', verbose_name=_('опрос'))
    question = models.ForeignKey('constructor.Question', on_delete=models.CASCADE, related_name='quiz_questions', verbose_name=_('опрос'))
    is_answered = models.BooleanField(default=False, verbose_name=_('на вопрос дан ответ?'))
    is_right_answered = models.BooleanField(default=False, verbose_name=_('на вопрос дан верный ответ?'))
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f'{self.quiz.username} | #{self.quiz.pk}'

    class Meta:
        verbose_name = _('вопрос в опросе')
        verbose_name_plural = _('вопросы в опросах')

src/quizzing/forms.py
from django import forms
from django.utils.translation import gettext_lazy as _

from constructor.models import Answer


class QuizQuestionForm(forms.Form):
    pk = forms.CharField(widget=forms.HiddenInput())
    answers = forms.ModelMultipleChoiceField(
        queryset=Answer.objects.all(),
        widget=forms.CheckboxSelectMultiple(),
        label=_('Варианты ответов'),
        error_messages={'required': _('Необходимо выбрать хотя бы один ответ.')},
    )

    def __init__(self, *args, **kwargs):
        question_pk = kwargs.pop('question_pk', None)
        super().__init__(*args, **kwargs)
        if question_pk:
            self.fields['answers'].queryset = Answer.objects.filter(question_id=question_pk)

src/quizzing/views.py
from logging import getLogger
from smtplib import SMTPException

from django.conf import settings
from django.core.mail import send_mail
from django.http import HttpResponseRedirect
from django.shortcuts import render, redirect
from django.urls import reverse
from django.utils.translation import gettext_lazy as _

from constructor.forms import LoginCreateQuizForm
from constructor.models import Subcategory
from .models import Quiz, QuizQuestion
from .forms import QuizQuestionForm

logger = getLogger('quizzing')


def select_quiz(request):
    quizzes = Quiz.objects.filter(is_completed=False)
    if request.POST:
        login_form = LoginCreateQuizForm(request.POST)
        if login_form.is_valid():
            if login_form.cleaned_data['password'] == settings.ADMIN_PANEL_PASSWORD:
                return redirect(reverse('constructor:create_quiz'))
    login_form = LoginCreateQuizForm()
    return render(request, 'quizzing/select_quiz.html', {
        'admin_panel_name': settings.ADMIN_PANEL_NAME,
        'quizzes': quizzes,
        'login_form': login_form,
    })


def pass_quiz(request, quiz_pk):
    if request.method == 'POST':
        form = QuizQuestionForm(request.POST)
        if form.is_valid():
            quiz_question = QuizQuestion.objects.get(pk=form.data['pk'])
            right_answers = list(quiz_question.question.answers.filter(is_right=True).values_list('pk', flat=True))
            user_answers = list(form.cleaned_data['answers'].values_list('pk', flat=True))
            if user_answers == right_answers:
                quiz_question.is_right_answered = True
            quiz_question.is_answered = True
            quiz_question.save()
        else:
            quiz_question = QuizQuestion.objects.get(pk=form.data['pk'])
            form = QuizQuestionForm(question_pk=quiz_question.question.pk)
            return render(request, 'quizzing/pass_quiz.html', {
                'form': form,
                'pk': quiz_question.pk,
                'subcategory': quiz_question.question.subcategory,
                'text': quiz_question.question.text,
                'error': _('Необходимо выбрать хотя бы один ответ.'),
            })
    else:
        quiz_questions = QuizQuestion.objects.filter(quiz_id=quiz_pk, is_answered=False).order_by('question__subcategory', '?')
        for quiz_question in quiz_questions:
            form = QuizQuestionForm(question_pk=quiz_question.question.pk)
            return render(request, 'quizzing/pass_quiz.html', {
                'form': form,
                'pk': quiz_question.pk,
                'subcategory': quiz_question.question.subcategory,
                'text': quiz_question.question.text,
                })
        # Display quiz results.
        quiz_questions = QuizQuestion.objects.filter(quiz_id=quiz_pk).order_by('question__subcategory', '?')
        subcategories = Subcategory.objects.filter(questions__quizzes=quiz_pk).distinct()
        username = Quiz.objects.get(id=quiz_pk).username
        results = [{
            'subcategory': subcategory,
            'total_questions': quiz_questions.filter(question__subcategory=subcategory).count(),
            'total_right_answered': quiz_questions.filter(question__subcategory=subcategory, is_right_answered=True).count(),
            } for subcategory in subcategories]
        if not Quiz.objects.get(id=quiz_pk).is_completed:
            try:
                results_text = ''.join([f"{result['subcategory']}: {result['total_right_answered']} / {result['total_questions']}\n" for result in results])
                is_successful = all(result['total_right_answered'] == result['total_questions'] for result in results)
                message = f"Результаты тестирования:\n{results_text}\nТест {'' if is_successful else 'не'} пройден!"
                send_mail(
                    f'Тестирование {username}',
                    message,
                    settings.EMAIL_HOST_USER,
                    [settings.ADMINISTRATOR_MAILBOX],
                    fail_silently=False,
                )
            except SMTPException as error:
                logger.error('Error while sending result of quiz to e-mail', exc_info=error)
        Quiz.objects.filter(id=quiz_pk).update(is_completed=True)
        return render(request, 'quizzing/stop_quiz.html', {
            'total_questions': Quiz.objects.get(id=quiz_pk).questions.count(),
            'total_right_answered': Quiz.objects.get(id=quiz_pk).quiz_questions.filter(is_right_answered=True).count(),
            'username': username,
            'results': results,
        })
    return HttpResponseRedirect(reverse('quizzing:pass_quiz', kwargs={'quiz_pk': quiz_pk}))

src/quizzing/templates/quizzing/pass_quiz.html
{% extends 'constructor/base.html' %}

{% block content %}
    <br>
    <form action="" method="post" class="form" novalidate>
        {% csrf_token %}

        {# Render hidden fields. #}
        {{ form.non_field_errors }}
        {{ form.pk.errors }}
        <input type="hidden" name="pk" id="id_pk" value="{{ pk }}">
        <div class="card text-dark bg-light mb-3" style="max-width: 1000px;">
            <div class="card-header">Блок: {{ subcategory }}</div>
            <div class="card-body">
                <h3 class="card-title">{{ text }}</h3>
                {# Render answers. #}
                <div class="invalid-feedback d-block">
                    {{ error }}
                </div>
                <p>
                    {{ form.answers }}
                </p>
            </div>
        </div>
        <button type="submit" class="btn btn-primary">Ответить</button>
    </form>
{% endblock %}

src/quizzing/templates/quizzing/select_quiz.html
{% extends 'constructor/base.html' %}

{% block content %}
    <br>
    <p>Выберите тест:</p>
    {# Render list of quizzes. #}
    <div class="list-group" style="max-width: 1000px;">
            {# Render admin panel entrance. #}
            <button type="button" class="list-group-item list-group-item-action btn btn-primary" data-bs-toggle="modal" data-bs-target="#login-modal"><pre>{{ admin_panel_name }}</pre></button>
            <div class="modal fade" id="login-modal" tabindex="-1" aria-labelledby="login-modal-label" aria-hidden="true">
                <div class="modal-dialog">
                    <div class="modal-content">
                        <div class="modal-header">
                            <h5 class="modal-title" id="login-modal-label">Введите пароль</h5>
                            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                        </div>
                        <form action="" method="post" class="form" novalidate>
                            <div class="modal-body">
                                    {% csrf_token %}
                                    {{ login_form }}
                            </div>
                            <div class="modal-footer">
                                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Закрыть</button>
                                <button type="submit" class="btn btn-primary">Отправить</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>

        {% for quiz in quizzes %}
            <a href="pass/{{ quiz.pk }}" class="list-group-item list-group-item-action"><pre>{{ quiz.username }}</pre></a>
        {% endfor %}
    </div>
{% endblock %}

src/quizzing/templates/quizzing/stop_quiz.html
{% extends 'constructor/base.html' %}

{% block content %}
    <br>
    <div class="card text-dark bg-light mb-3" style="max-width: 1000px;">
        <div class="card-header">Тестирование: {{ username }}</div>
        <div class="card-body">
            <h3 class="card-title">Результаты тестирования:</h3>
            <p>
                {% for result in results %}
                    {% if result.total_right_answered == result.total_questions %}
                        {{ result.subcategory }}: <span class="text-success">{{ result.total_right_answered }} / {{ result.total_questions }}</span>
                    {% else %}
                        {{ result.subcategory }}: <span class="text-danger">{{ result.total_right_answered }} / {{ result.total_questions }}</span>
                    {% endif %}
                <br>
                {% endfor %}
            </p>
        </div>
    </div>
{% endblock %}